---
title: "Final Project Stuff"
output: pdf_document
date: "2023-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
data <- read.csv('case_study_data.csv')
options(scipen = 999, digits = 6)
hist(data$Pct_Change_Dec2007_June_2009)
summary(data$Pct_Change_Dec2007_June_2009)
```

```{r}
data
```


```{r}
filtered_data <- data %>%
  filter(Pct_Change_Dec2007_June_2009 < abs(500) & Pct_Change_Dec2009_June_2011 < abs(500))

filtered_data

# Create a histogram with custom aesthetics
ggplot(filtered_data, aes(x = Pct_Change_Dec2007_June_2009)) +
  geom_histogram(binwidth = 20, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(
    title = "Histogram of Percentage Change (Dec 2007 to June 2009)",
    x = "Percentage Change",
    y = "Frequency"
  ) +
  theme_minimal()
```

```{r}
nrow(filtered_data)
nrow(data)
```

The block below is not used.
```{r}
#library(MASS)
#transformed_x <- boxcox(filtered_data$Pct_Change_Dec2007_June_2009)
#lambda <- transformed_x
#transformed_data <- x ^ lambda
```

All models commented out were excluded in favor of the one remaining model.
```{r}
#model <- lm(Pct_Change_Dec2009_June_2011 ~Pct_Change_Dec2007_June_2009, data = filtered_data)
#plot(model)

#min(filtered_data$Pct_Change_Dec2007_June_2009)

model_2 <-  lm(Pct_Change_Dec2009_June_2011 ~ log(Pct_Change_Dec2007_June_2009 +99.5+1), data = filtered_data)

plot(model_2)

original_x <- filtered_data |> pull(Pct_Change_Dec2007_June_2009)
filtered_data$Transformed_Variable <- log(original_x + 99.5 + 1)
#filtered_data$Transformed_Variable <- filtered_data$Pct_Change_Dec2007_June_2009^(1/3)

#model_3 <- lm(Pct_Change_Dec2009_June_2011 ~ Transformed_Variable, data = filtered_data)

#plot(model_3)
```
```{r}
summary(model_2)


observed_slope <- summary(model_2)$coeff[2, 3]

```

If we did a hypothesis test, we would reject the null hypothesis that $\beta_1=0$ since we get a p value of close to zero.

## Permutation Test

```{r}
num_permutations <- 10000

# Create an array to store permuted slopes
permuted_slopes <- numeric(num_permutations)

# Original observed slope
observed_slope <- summary(model_2)$coeff[2, 3]

# Permutation test loop
for (i in 1:num_permutations) {
  # Permute the independent variable
  permuted_x <- sample(filtered_data$Transformed_Variable)
  
  # Fit a linear model with the permuted data
  permuted_lm <- lm(filtered_data$Pct_Change_Dec2009_June_2011 ~ permuted_x)
  
  # Store the permuted slope
  permuted_slopes[i] <- summary(permuted_lm)$coeff[2, 3]
}

# Calculate the p-value
p_value <- mean(abs(permuted_slopes) >= abs(observed_slope))
```

```{r}
p_value
```

